name: Release

on:
  pull_request:
  push:
    branches:
      - "v[0-9]+"

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63
      - uses: volta-cli/action@v3
        with:
          node-version: 14
          yarn-version: 1.22.19
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - name: Publish Releases
        uses: thefrontside/actions/synchronize-with-npm@tm/allow-publish-script
        with:
          PUBLISH_SCRIPT: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
