name: Release

on:
  push:
    branches:
      - "v[0-9]+"

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63
      - uses: volta-cli/action@v3
        with:
          node-version: 14
          yarn-version: 1.22.19
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - name: Publish Releases
        uses: thefrontside/actions/synchronize-with-npm@v2
        with:
          npm_publish: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
