name: Release

on:
  push:
    branches:
      - "v[0-9]+"

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: windows-latest
    steps:
      - name: Install Rust Toolchain
        run: |
          rustup install 1.63.0
          rustup default 1.63.0
          rustup target add x86_64-pc-windows-msvc
          rustup target add aarch64-pc-windows-msvc
      - uses: volta-cli/action@v3
        with:
          node-version: 14
          yarn-version: 1.22.19
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build --arch=arm64
      - run: yarn build --arch=x64
      - name: Publish Releases
        uses: thefrontside/actions/synchronize-with-npm@v2
        with:
          npm_publish: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
