name: Release

on:
  push:
    branches:
      # - 'v[0-9]+'
      - mk/publish

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Releases
      uses: thefrontside/actions/synchronize-with-npm@v1.6
      with:
        before_all: yarn clean
        npm_publish: yarn publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.FRONTSIDEJACK_NPM_TOKEN }}
