name: Test

on:
  pull_request:
    branches:
      - 'v[0-9]+'

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }} test node@${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        node: [10, 12, 14, 16]
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      - run: yarn install --ignore-scripts
      - run: yarn build release
      - run: yarn test
