name: Test

on:
  pull_request:
    branches:
      - "v[0-9]+"

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }} test node@${{ matrix.node-version }}
    strategy:
      matrix:
        platform: [windows-latest]
        node-version: ["12", "14", "16"]
      fail-fast: false
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn config set python python2.7
      - run: yarn config set msvs_version 2015
      - run: yarn install --ignore-scripts
      - run: yarn build release
      #   env:
      #     RUST_BACKTRACE: 1
      # - run: yarn neon build --release
      # - run: cargo build --release --bin killer
      # - run: |
      #     cp native/target/release/killer.exe dist
      #     cp native/index.node dist
      - run: yarn test
