name: Upload Binaries

on: pull_request

jobs:
  upload-binary:
    name: Upload Assets (node ${{ matrix.node-version }})
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ['10', '12', '14', '16']
      fail-fast: false
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
          yarn-version: 1.22.5
      - run: yarn install --ignore-scripts
      - run: yarn build release
      - run: yarn node-pre-gyp package
